# INTERFACE/translations.py

translations = {
    'fr': {
        'app_title':    "DÉTECTEUR DE MÉLANOME",
        'import':       "CHOISIR UNE IMAGE",
        'label': "Partie du corps/numéro Photo",
        'analyse':      "ANALYSER",
        'detected':     "MÉLANOME DÉTECTÉ",
        'not_detected': "PAS DE MÉLANOME",
        'confidence':   "Confiance",
        'no_image':     "Aucune image chargée",
        'disclaimer':   "Note : Cet outil ne remplace pas un examen médical.\nSeul un professionnel de santé peut poser un diagnostic définitif.",
        'more_info':    "En savoir plus",
        'show_clear':   "VOIR IMAGE NETTE",
        'show_blur':    "REFLOUTER IMAGE",
        'add_profile':  "Ajouter profil",
        'delete_profile': "Supprimer profil",
        'new_nom':      "Nom",
        'new_prenom':   "Prénom",
        'new_age':      "Âge",
        'new_taille':   "Taille (cm)",
        'new_poids':    "Poids (kg)",
        'save':         "Enregistrer",
        'cancel':       "Annuler",
        'history':      "Historique",
        'no_result': "PAS DE RESULTAT",

    },
    'en': {
        'app_title':    "MELANOMA DETECTOR",
        'import':       "SELECT IMAGE",
        'label': "Body part/Photo number",
        'analyse':      "ANALYZE",
        'detected':     "MELANOMA DETECTED",
        'not_detected': "NO MELANOMA",
        'confidence':   "Confidence",
        'no_image':     "No image loaded",
        'disclaimer':   "Note: This tool does not replace a medical examination.\nOnly a healthcare professional can make a definitive diagnosis.",
        'more_info':    "Learn more",
        'show_clear':   "SHOW CLEAR IMAGE",
        'show_blur':    "REBLUR IMAGE",
        'add_profile':  "Add profile",
        'delete_profile': "Delete profile",
        'new_nom':      "Last name",
        'new_prenom':   "First name",
        'new_age':      "Age",
        'new_taille':   "Height (cm)",
        'new_poids':    "Weight (kg)",
        'save':         "Save",
        'cancel':       "Cancel",
        'history':      "History",
        'no_result': "NO RESULT",
    }
}
